---
title: "GP120-rabbit analysis-> Figure 6"
author: 
  - "Richard Barfield"
  - "Biostatistics, Epidemiology and Research Design (BERD) Core"
  - "Center for Human Systems Immunology (CHSI)"
date: "`r  Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r Baseinfo,eval=FALSE}
#General info ----------------------
#
# Created: 2022-02-03
#
# Author: Richard Barfield
#
# Program: Code/15_Figure_6_analyses.R
#
# Description: Analyses for Figure 6
#                
#--- --- --- --- --- --- --- --- --- --- --- --- --- 
#--- --- --- --- --- --- --- --- --- --- --- --- --- 
```

```{r libs,message=FALSE, warning=FALSE, include=F, results='asis'}

library(lubridate)
library(DescTools)
library(coin)

library(geepack)
library(gee)
library(geesmv)

library(ggfortify)
library(rcompanion)

library(nparLD)
library(table1)
library(readxl)
library(tidyxl)
library(knitr)
library(kableExtra)
library(tidyverse)

```

# Introduction

Reading in and processing the data into an analytical form to be used

# Path to Data

```{r loaddata}



pathtofile<-"Data/Processed/"
pathtofile<-file.path(getwd(),"../",pathtofile)



#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Load the data
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Fig3.data<-readRDS(file.path(pathtofile,
                             "0_data_processed_fig5.RDS"))

#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# ADding information on what "vaccine group" in
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
OurVaccine.info<-read.delim(text = "Rabbit	Vaccine
N32330	gp120+STR8S-C (-Q11)
N32331	gp120+STR8S-C (-Q11)
N32332	gp120+STR8S-C (-Q11)
N32333	gp120+STR8S-C (-Q11)
N32334	gp120+STR8S-C (-Q11)
N32335	gp120+STR8S-C (-Q11)
N32336	gp120+STR8S-C (-Q11)
N32337	gp120+STR8S-C (-Q11)
N32338	gp120-Q11+STR8S-C (+Q11)
N32339	gp120-Q11+STR8S-C (+Q11)
N32340	gp120-Q11+STR8S-C (+Q11)
N32341	gp120-Q11+STR8S-C (+Q11)
N32342	gp120-Q11+STR8S-C (+Q11)
N32343	gp120-Q11+STR8S-C (+Q11)
N32344	gp120-Q11+STR8S-C (+Q11)
N32345	gp120-Q11+STR8S-C (+Q11)",sep="\t")


```

# Figure 6B

First visualization (only 16, there is a duplcate metabolite in plot in SAP).

```{r Aim42analysis, echo=F,fig.height=12,fig.width=12}



#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Get the week 0 values
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


wk0_total_IgG<-Fig3.data$Figure5_total_wk0 %>% 
  filter(str_detect(name,"IgG",negate=T)) %>% 
  left_join(OurVaccine.info %>% rename(ID=Rabbit)) %>% 
  filter(What_Is=="Individual")

#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Get the week 14 glycal gp120
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
wk14_glycal_gp120<-Fig3.data$Figure5_glycan %>% 
  filter(str_detect(name,"IgG",negate=T)) %>% 
  left_join(OurVaccine.info %>% rename(ID=Rabbit))

#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Set up basis of analyses
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Analysis<-wk14_glycal_gp120%>% 
  mutate(name=ifelse(name=="G1FB[6]/G1F[3]","G1F[3]/G1FB[6]",name))

Analysis %>% ggplot(aes(x=Vaccine,y=MeanValue))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(position=position_jitter(0.1,seed=20210941),
             aes(col=CV>0.2))+
  facet_wrap(~name,nrow=4,ncol=4,scales="free_y")+
  theme(axis.text.x = element_text(size=6,angle=90))



```


There is a good amount of data (`r sum(Analysis$CV>0.2)` ) where the CV being greater than 0.2. Will be using all data, regardless of this.


```{r dividewk0, options}

NewAnalysis<-Analysis %>% 
  left_join(wk0_total_IgG %>% select(ID,name,wk0val=MeanValue)) %>% 
  mutate(MeanValue=MeanValue/wk0val)%>% 
  group_by(name) %>% 
  mutate(Vaccine=as.factor(Vaccine)) %>% 
  summarize(Pvalue=pvalue(wilcox_test(MeanValue ~ Vaccine,dist="exact"))[1]) %>% 
  mutate(FDR.adjust=p.adjust(Pvalue,"BH")) %>% 
  arrange(Pvalue)

NewAnalysis %>% select(name,AdjWk0Pvalue=Pvalue,FDR.adjust) %>% 
  DT::datatable(rownames=F) %>% 
  DT::formatSignif(c("FDR.adjust","AdjWk0Pvalue"))

```


# Spearman correlation values


```{r somecor, options}

SomeCor<-Fig3.data$Figure5_heatmap %>% 
  mutate(name=str_remove_all(name," IgG%")) %>% 
  mutate(name=ifelse(name=="Bissected","Bisected",name)) %>% 
  mutate(name=ifelse(name=="agalactosylated","Agalatosylated",name)) %>% 
  filter(name!="Neutralization_CH505w4.3")
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Like everything this will take some coding 
# 
# First the gp120 wk14 values
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


D1<-SomeCor %>% filter(name %in% c("ADCC_gp120 T/F_wk21",
                                    "G1FS1(2,6)", 
                                    "A1F(2,6)",
                                    "A2FB(2,6)", 
                                    "G1F[6]", 
                                    "G1FB[6]/G1F[3]",
                                    "Mono-galactosylated",
                                    "Fucosylated",
                                    "A1F(2,6)",
                                    "G1F[3]/G1FB[6]",
                                    "G1FS1(2,6)",
                                    "G1[3]",
                                    "G0F",
                                    "G2",
                                    "A1FB(2,6)",
                                    "G1F[6]",
                                    "G2F")) %>% 
  select(`Animal ID`,What,name,value) %>% 
  arrange(name)

D2<-D1 %>% filter(str_detect(name,"ADCC",negate=T)) %>% 
  left_join(D1 %>% filter(str_detect(name,"ADCC",negate=F)) %>% 
              select(-name) %>% 
              rename(ADCC=value))
  



#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Calculate the correlation
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


set.seed(41419)
my.func<-function(ww,nn){
  tt<-D2 %>% filter(What==ww & name==nn)
  return(spearmanRho(~value+ADCC,ci=T,data=tt,type="perc",R=1000))
}


GG<-D2 %>% select(What,name) %>% 
  distinct() %>% group_by(What,name) %>% 
  summarize(ss=my.func(ww=What,nn=name),.groups="drop") %>% 
  unpack(ss)



 KeepHere<-GG %>%
      mutate(fakelabel=paste0(name,"_",What)) %>% 
      mutate(newfakelabel=fct_rev(fakelabel)) %>% 
      arrange(fakelabel)
    
    KeepHere %>% 
        ggplot(aes(x=(newfakelabel),
                             y=`rho`,
                             ymin=lower.ci,ymax=upper.ci,
                             col=What))  +
        geom_pointrange() + 
        coord_flip() +  
        xlab("Metabolite") + ylab("rho (95% Bootstrap CI)") +
        theme_bw()  +
        scale_x_discrete(breaks=KeepHere$fakelabel[seq(1,nrow(KeepHere),
                                                 by=3)],
                         labels=KeepHere$name[seq(1,nrow(KeepHere),
                                                 by=3)])+
      ggtitle("Correlation with ADCC to gp120 at week 21")
    
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Calculating the additional correlation 
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---    
    
GG %>% mutate(Estimate_and_CI=paste0(formatC(rho,3)," (",
                                 formatC(lower.ci,3),", ",
                                 formatC(upper.ci,3),")"))  %>% 
  filter(What=="gp120-specific wk14") %>% select(What,name,Estimate_and_CI) %>% 
  arrange(name) %>% 
  kable(caption="Correlation Just IgG week14") %>% 
  kable_styling(full_width = F)
```

# Session Info

```{r sessioninfo}
sessionInfo()
```
