---
title: "GP120-rabbit analysis-> Supplementary Figures"
author: 
  - "Richard Barfield"
  - "Biostatistics, Epidemiology and Research Design (BERD) Core"
  - "Center for Human Systems Immunology (CHSI)"
date: "`r  Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r Baseinfo,eval=FALSE}
#General info ----------------------
#
# Created: 2022-02-03
#
# Author: Richard Barfield
#
# Program: Code/16_SFigures_analyses.R
#
# Description: Analyses for Supplement figures
#                
#--- --- --- --- --- --- --- --- --- --- --- --- --- 
#--- --- --- --- --- --- --- --- --- --- --- --- --- 
```

```{r libs,message=FALSE, warning=FALSE, include=F, results='asis'}

library(lubridate)
library(DescTools)
library(coin)

library(geepack)
library(gee)
library(geesmv)

library(ggfortify)
library(rcompanion)
library(ComplexHeatmap)
library(RColorBrewer)
library(nparLD)

library(readxl)
library(tidyxl)
library(knitr)
library(kableExtra)
library(tidyverse)

```

# Introduction

Reading in and processing the data into an analytical form to be used

# Path to Data

```{r loaddata}



pathtofile<-"Data/Processed/"
pathtofile<-file.path(getwd(),"../",pathtofile)




#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# ADding information on what "vaccine group" in
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
OurVaccine.info<-read.delim(text = "Rabbit	Vaccine
N32330	gp120+STR8S-C (-Q11)
N32331	gp120+STR8S-C (-Q11)
N32332	gp120+STR8S-C (-Q11)
N32333	gp120+STR8S-C (-Q11)
N32334	gp120+STR8S-C (-Q11)
N32335	gp120+STR8S-C (-Q11)
N32336	gp120+STR8S-C (-Q11)
N32337	gp120+STR8S-C (-Q11)
N32338	gp120-Q11+STR8S-C (+Q11)
N32339	gp120-Q11+STR8S-C (+Q11)
N32340	gp120-Q11+STR8S-C (+Q11)
N32341	gp120-Q11+STR8S-C (+Q11)
N32342	gp120-Q11+STR8S-C (+Q11)
N32343	gp120-Q11+STR8S-C (+Q11)
N32344	gp120-Q11+STR8S-C (+Q11)
N32345	gp120-Q11+STR8S-C (+Q11)",sep="\t")


```

# Figure S6A

First visualization (only 16, there is a duplcate metabolite in plot in SAP).

```{r Aim42analysis, echo=F,fig.height=12,fig.width=12}


#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Load the data
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Fig3.data<-readRDS(file.path(pathtofile,
                             "0_data_processed_fig4.RDS"))





```

There is data that is above the CV cutoff of 0.2 that is dropped and then this info was then rerun. 

```{r cvanalysis, options}


Fig3.binding<-Fig3.data$Figure4_binding

ToDrop<-sum(Fig3.binding$CV >0.20)

Fig3.binding %>% filter(CV>=0.2) %>% 
  kable() %>% kable_styling(full_width = F)



```


## Run the analysis

```{r analysisFigS6A, options}


Fig3.binding.analysis<-Fig3.binding %>% 
  filter(CV<0.2) %>% 
  mutate(Description=str_remove_all(Description,"R")) %>% 
  mutate(Rabbit=str_split_fixed(Description,"_",2)[,1],
         Week=str_split_fixed(Description,"_",2)[,2]) %>% 
  mutate(TheBinding=str_split_fixed(What,"wk",2)[,2]) %>% 
  mutate(TheBinding=str_split_fixed(TheBinding,"14_",
                                    2)[,2]) %>% 
  mutate(TheBinding=str_remove_all(TheBinding,".xlsx")) %>% 
  mutate(TheBinding=str_remove_all(TheBinding,
                                   "(PL[[:alnum:]])")) %>% 
  mutate(TheBinding=str_remove_all(TheBinding,"_"))

Fig3.binding.analysis<-Fig3.binding.analysis %>% 
  mutate(TheBinding=ifelse(str_detect(TheBinding,"FcR"),
                           TheBinding,
                           paste0("FcR",TheBinding))) %>% 
  mutate(TheBinding=str_remove_all(TheBinding,
                                   "[[:blank:]]"))
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# If there is more than one (due to sample sample as opposed to the population sample for CV)
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

Fig3_fin_binding<-Fig3.binding.analysis %>% 
  mutate(DateRun=str_split_fixed(What,"_",2)[,1]) %>% 
  group_by(TheBinding,Week,Rabbit) %>% 
  arrange(desc(ymd(DateRun))) %>% 
  slice(1) %>% ungroup() %>% 
  select(Rabbit,Week,Value=Mean_val,TheBinding) %>% 
  left_join(OurVaccine.info)



#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Run the p-value
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---  



Opvalue<-Fig3_fin_binding %>% 
   group_by(TheBinding,Week) %>% 
   summarize(pvalue_coin_exact=pvalue(wilcox_test(Value~as.factor(Vaccine),
            distribution="exact"))[1],
            .groups="drop") %>% 
  mutate(FDR_Pvalue=p.adjust(pvalue_coin_exact,"BH"))

Opvalue %>% 
  mutate(Week=factor(Week,levels=c("wk2","wk8","wk14"))) %>% 
  arrange(Week) %>% 
  DT::datatable(rownames=F) %>% 
  DT::formatSignif(c("pvalue_coin_exact","FDR_Pvalue"),3)



```

# Figure S6B


```{r FigS6B, options}



Fig3.data<-readRDS(file.path(pathtofile,
                             "0_data_processed_fig4_additional.RDS"))


Other.data<-Fig3.data$Figure4_FCR %>% 
  mutate(`Rabbit`=paste0("N",`Animal ID`)) %>% 
  left_join(OurVaccine.info)


OurPvalues<-Other.data %>% 
  group_by(What) %>% 
   summarize(pvalue=pvalue(wilcox_test(Mean~as.factor(Vaccine),
            distribution="exact"))[1],
            .groups="drop") %>% 
  mutate(FDR_Pvalue=p.adjust(pvalue,"BH"))

OurPvalues%>% 
  DT::datatable(rownames=F) %>% 
  DT::formatSignif(c("pvalue","FDR_Pvalue"),3)
```




# Figure S8A

```{r FigS8A, echo=F}

Fig3.data<-readRDS(file.path(pathtofile,
                             "0_data_processed_fig4.RDS"))


Aim32<-Fig3.data$Figure4_spr

#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Setting data to lower bound
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
ForAnalysis<-Aim32 %>% filter(name %in% c("kd","Avidity")) %>% 
  mutate(Newvalue=ifelse(name=="kd" & AtLowerBound==1,Newvalue/2,Newvalue)) %>% 
  rename("subject"=Sample) %>% 
  left_join(OurVaccine.info %>% rename("subject"=Rabbit)) %>% 
  mutate(Week=as.character(Week))

Resu.KD<-nparLD(Newvalue~Week+Vaccine,time1.order = c("2","8","14"),
                          subject = "subject",order.warning = F,
                          description = F,
                          data=ForAnalysis %>% filter(name=="kd"))
            
 
Resu.Avid<-nparLD(Newvalue~Week+Vaccine,time1.order = c("2","8","14"),
                          subject = "subject",order.warning = F,
                          description = F,
                          data=ForAnalysis %>% filter(name!="kd"))
            
 

            

data.frame(Pvalues=c(signif(Resu.KD$ANOVA.test.mod.Box[4],3),
                     signif(Resu.Avid$ANOVA.test.mod.Box[4],3))) %>% 
  mutate(What=c("kd","Avidiity")) %>% 
  select("What","Pvalues") %>% 
  kable() %>% kable_styling(full_width = F)



ForAnalysis %>% 
  mutate(AtBound=ifelse(AtUpperBound==1|AtLowerBound==1,"At Bound","Not At Bound")) %>% 
  mutate(Week=factor(Week,levels=c("2","8","14"))) %>% 
  ggplot(aes(x=Week,y=Newvalue,col=Vaccine))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(position = position_jitterdodge(0.1,seed=20210895))+
  facet_wrap(~name,nrow=2,scales = "free_y")+
  scale_y_log10()

```


# Figure S8B

```{r FigureS8B, }
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# source code 
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
source("1_general_code_for_calc_BC_variance.R")



HoldThis<-readRDS(file.path(pathtofile,
                             "0_data_processed_fig2.RDS"))
Fig3.Bama <- HoldThis$Figure2_BAMA

Fig3.Bama.Analyze<-Fig3.Bama %>% select(Rabbit=RabbitID,Week,
                     c1086V1V2=`c1086 V1/V2 tag (20)`,
                     V3C=`Bio-V3.C (45)`,
                     C1=`C1-biotin (51)`,
                     V21086=`Bio-V2.1086.c (42)`,
                     C5.2C=`Bio. Rv144.C5.2C (43)`) %>% 
  left_join(OurVaccine.info) %>% 
  pivot_longer(cols=c(-Rabbit,-Week,-Vaccine)) 



Fig3.Bama.Analyze %>% 
  filter(!is.na(value)) %>% 
  ggplot(aes(x=name,y=value,col=Vaccine))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(position=position_jitterdodge(0.1))+
  facet_wrap(~Week,ncol=3)+
  scale_y_log10()+
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 90))+
  xlab("")+
  ylab("MFI")
  

#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Do this analyses using code from the BAMA analysis with gp120
# From Programs/GitCode/26_BAMA_multivalency_20200831
#--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


ForGee<-Fig3.Bama.Analyze %>% ungroup() %>%
  filter(!is.na(value)) %>% 
  mutate(BB=log10(value)) %>%
  mutate(NewMouse=factor(Rabbit)) %>% 
  mutate(Week=as.character(Week)) %>% 
  mutate(Vaccine=ifelse(str_detect(Vaccine,"gp120-Q11"),1,0)) %>% 
  mutate(Week=factor(Week,levels=c("2","8","14")))





```

# Session Info

```{r sessioninfo}
sessionInfo()
```
